### ISSUE TITLE
[Errno 2] No such file or directory: 'sass-convert'

### ISSUE THREAD

**Issue by smlombardi** [badsyntax/SassBeautify#111]
Trying to run plugin on scss file.  get this error. ST3 build 3107, OSX 10.11. Ruby sass 3.4.18.

![screen shot 2016-03-04 at 2 18 51 pm](https://cloud.githubusercontent.com/assets/835148/13537728/5b778ce0-e214-11e5-9a6f-f3469a97bede.png)

**Comment by DevProse** [comment]
This worked for me and is a slight deviation from the instructions

In terminal:

echo $PATH

put contents in "path" : option

echo $GEM_PATH

put contents in "gemPath" : option

THEN (**here is the fix**) in terminal type:

which ruby

you should get something like:

/Users/devprose/.rvm/rubies/ruby-2.2.0/bin/ruby

Then add that to the end of the "path" option by placing a semicolon before it like so:

:/Users/devprose/.rvm/rubies/ruby-2.2.0/bin/ruby

*_NOTE: *_ I was able to get it to work without exporting my entire path and only placing the results of 'which ruby' in the "path" option, but I'd advise following the author's instructions just in case and just augmenting it with this little add on as needed.  Appears to be a Mac specific issue.

**Comment by badsyntax** [comment]
I have had so many problems with rvm and paths, i really don't know what to advise people. I am not a ruby dev and I don't understand a lot of things related to ruby and rvm specifically. Thank you for this information though, hopefully it will help others.

**Comment by smlombardi** [comment]
Thanks.  I went back to Atom, since things like this "just work" out of the box.

**Comment by tsai-jimmy** [comment]
@badsyntax 
Maybe you can fellow this step.. 
http://tsai-jimmy.logdown.com/posts/1295269-sassbeautify-errno-2-no-such-file-or-directory-sass-convert

**Comment by felixprojekt** [comment]
Try:
Under Preferences > Package Settings > SassBeautify > Settings – User add this line:

```
{
	"path": "/usr/local/bin",
}
```

**Comment by ArielBeninca** [comment]
hey this does not work for me 

{
	"path": "/usr/local/bin",
}

did not work and 

echo $GEM_PATH

returns nothing

**Comment by field2** [comment]
This seems to happen every time you update MacOS.
Try running
`sudo gem install sass` in the terminal to fix.

**Comment by field2** [comment]
After years of the install sass fix working, and now with an M1 MacBook/Ventura 13.4 there's a new error:

There was an error beautifying your Sass:

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin22/rbconfig.rb:21:in ``': No such file or directory - uname (Errno::ENOENT)
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin22/rbconfig.rb:21:in `<module:RbConfig>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin22/rbconfig.rb:11:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:9:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:9:in `<top (required)>'
from <internal:gem_prelude>:2:in `require'
from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
