### ISSUE TITLE
Encoding Errors on a Russian System

### ISSUE THREAD

**Issue by vladipus** [badsyntax/SassBeautify#74]
Getting the following error, when running on a Russian Windows 7:

    Traceback (most recent call last):
    File "SassBeautify in C:\Users\Vladislav\AppData\Roaming\Sublime Text 3\Installed Packages\SassBeautify.sublime-package", line 198, in <lambda>
    File "SassBeautify in C:\Users\Vladislav\AppData\Roaming\Sublime Text 3\Installed Packages\SassBeautify.sublime-package", line 201, in check_thread
    File "SassBeautify in C:\Users\Vladislav\AppData\Roaming\Sublime Text 3\Installed Packages\SassBeautify.sublime-package", line 212, in handle_process
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 15: invalid start byte

**Comment by badsyntax** [comment]
Please paste the content which is causing this error.

**Comment by vladipus** [comment]
It seems the problem is not content at all, but the missing `sass-convert` executable. I suggest this change at start of `handle_process(self, returncode, output, error)`:

        import locale
        os_encoding = locale.getpreferredencoding()
        print("System encoding: " + os_encoding)


        if type(output) is bytes:
            try:
                output = output.decode('utf-8')
            except UnicodeDecodeError:
                output = output.decode(os_encoding, errors='replace')

        if type(error) is bytes:
            try:
                error = error.decode('utf-8')
            except UnicodeDecodeError:
                error = error.decode(os_encoding, errors='replace')

This still shows me invalid characters, but at least doesn't fail silently:
![2015-02-10 18_40_28-p__projects local_vdt_software_apps_third-party_tellmebest_app cordova_www src_s](https://cloud.githubusercontent.com/assets/468323/6130159/6349738a-b154-11e4-9150-31c878c06fd4.png)

**Comment by badsyntax** [comment]
Thanks for this. It would be ideal if we could decode those Russian characters correctly. When I have some time I'll look into this some more. Thanks for the report.

**Comment by vladipus** [comment]
You are welcome. I would also be glad to have real Cyrillic characters. Unfortunately I have no specific idea on how to achieve this. Maybe Sublime's environment spoils something in the middle, maybe not. The `locale.getpreferredencoding()` seems to return the correct encoding for the system, but maybe the bytes actually contain MS-Unicode 16-bit chars. If you need testing on your variants on a Russian system, let me know.

**Comment by Alecto** [comment]
the same error for me
